### ISSUE TITLE
Bug: Input char for posts and comments should be limited in frontend and backend, so we ensure to have a stable system

### ISSUE THREAD

**Issue by Mariinja** [The-Agile-Avengers/icu-connect-frontend#172]

**Comment by solodezaldivar** [comment]
@Mariinja do we already have length values which we want to enforce?

**Comment by StefanieKrohmann** [comment]
I set some values, see here: https://github.com/The-Agile-Avengers/icu-connect-frontend/commit/0297af60f6152b1952e1c5f1655b838ffbc8a7bd
